version: "{build}"

environment:
  global:
    RUST_VERSION: stable

  matrix:
    # chemfiles does not work with GNU target yet
    # - TARGET: i686-pc-windows-gnu
    # - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
    - cargo build --target %TARGET%
    - cargo bench --no-run --target %TARGET%

test_script:
    # Run unit tests and doc tests in debug mode
    - cargo test --target %TARGET% -p lumol-core
    - cargo test --target %TARGET% -p lumol-input
    # Run all tests in release mode
    - cargo test --target %TARGET% --all --release

cache:
  - C:\Users\appveyor\.cargo\registry
  - target
